site_name: My projects / Moje projekty
site_author: Adam Musiał
site_description: >-
    Portfolio for Data Science, AI Projects and Frontend Projects by Adam Musiał.

repo_name: Adam-Musial-AMu/portfolio
repo_url: https://github.com/Adam-Musial_AMu/portfolio

theme:
  name: material
  features:
    - content.tabs.link

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
- Homepage: index.md
- Data/AI/ML projects:
  - "Runner_app": runner_app_scc/index.md
  - "Lingoduo_app": lingoduo/index.md
  - "Titanic EDA": titanic/index.md
  - "Iris EDA": iris/index.md
- Frontend, Data & AI Portfolio:
  - "Full Portfolio Site": full_portfolio/index.md
  