site_name: Moje projekty
site_author: Adam Musiał
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: Adam-Musial-AMu/portfolio
repo_url: https://github.com/Adam-Musial_AMu/portfolio

theme:
  name: material
  features:
    - content.tabs.link

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
- Homepage: index.md
- Data/AI/ML projects:
  - "Lingoduo_app": lingoduo/index.md
  - "Titanic EDA": titanic/index.md
  - "Iris EDA": iris/index.md
- Frontend, Data & AI Portfolio:
  - "Full Portfolio Site": full_portfolio/index.md
  